name: Build Termux AI

on:
  push:
    branches: [ master, feat/codex-ai-preload ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Verify environment
      run: make doctor
      
    - name: Build debug APK (aarch64-only)
      run: make build
      
    - name: Run lint checks
      run: make lint || echo "Lint warnings found, continuing..."
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: termux-ai-debug-apk
        path: app/build/outputs/apk/debug/termux-app_*_arm64-v8a.apk
        
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build release APK (aarch64-only)
      run: make clean lint release
      
    - name: Upload release APK
      uses: actions/upload-artifact@v4
      with:
        name: termux-ai-release-apk
        path: app/build/outputs/apk/release/termux-app_*_arm64-v8a.apk